SET PAGES 50000
SET LINES 120
 
SET MARKUP HTML ON
 
SPOOL ANY_PRIVS.html
SELECT PRIVILEGE,GRANTEE FROM DBA_SYS_PRIVS WHERE PRIVILEGE LIKE '%ANY%'
ORDER BY 1,2;
SPOOL OFF
 
SPOOL PROD_ACCESS.html
SELECT * FROM DBA_TAB_PRIVS WHERE PRIVILEGE = ANY ('INSERT', 'UPDATE', 'DELETE')
ORDER BY 1,2;
SPOOL OFF
 
SPOOL DBA_SYS_PRIVS.html
SELECT * FROM DBA_SYS_PRIVS ORDER BY 1,2;
SPOOL OFF
 
SPOOL DBA_TAB_PRIVS.html
SELECT OWNER, TABLE_NAME, GRANTEE, PRIVILEGE, GRANTABLE, GRANTOR, HIERARCHY 
FROM DBA_TAB_PRIVS ORDER BY 1,2,3,4;
SPOOL OFF
 	
SPOOL DBA_COL_PRIVS.html
SELECT OWNER, TABLE_NAME, COLUMN_NAME, GRANTEE, PRIVILEGE, GRANTABLE, GRANTOR 
FROM DBA_COL_PRIVS ORDER BY 1,2,3,4,5;
SPOOL OFF
 
SPOOL DBA_ROLE_PRIVS.html
SELECT * FROM DBA_ROLE_PRIVS ORDER BY 1,2;
SPOOL OFF	
 
SPOOL UNIFIED_AUDIT_CONFIG.html

SELECT
  parameter,
  value
FROM v$option
WHERE parameter = 'Unified Auditing';

SPOOL OFF

SPOOL UNIFIED_AUDIT_POLICY.html

SELECT
  policy_name,
  enabled_option,
  entity_name,
  entity_type,
  success,
  failure
FROM audit_unified_enabled_policies
ORDER BY policy_name;

SPOOL OFF

 
SPOOL ROLE_ROLE_PRIVS.html
SELECT * FROM ROLE_ROLE_PRIVS ORDER BY 1,2;
SPOOL OFF
 
SPOOL DBA_USERS.html
SELECT USERNAME, USER_ID, ACCOUNT_STATUS, LOCK_DATE, EXPIRY_DATE,
	DEFAULT_TABLESPACE, TEMPORARY_TABLESPACE, CREATED, PROFILE,
	INITIAL_RSRC_CONSUMER_GROUP, EXTERNAL_NAME
FROM DBA_USERS ORDER BY 1;
SPOOL OFF
 
SPOOL DBA_ROLES.html
SELECT * FROM DBA_ROLES ORDER BY 1,2;
SPOOL OFF
 
SPOOL DBA_PROFILES.html
SELECT * FROM DBA_PROFILES ORDER BY 1,2;
SPOOL OFF
 
SPOOL V_PARAMETER.html
SELECT * FROM V$PARAMETER ORDER BY 2;
SPOOL OFF
 
SPOOL INVALID.html
SELECT owner, COUNT(*)
FROM dba_objects
WHERE STATUS='INVALID'
GROUP BY owner
ORDER BY 1;
SPOOL OFF
 
SPOOL INVALID_DETAIL.html
SELECT object_type,owner,object_name
FROM dba_objects
WHERE STATUS='INVALID' ORDER BY 1,2,3;
SPOOL OFF
 
SET MARKUP HTML OFF
