import re
import os
import gzip
import argparse
import geoip2.database
from collections import defaultdict
from datetime import datetime
from concurrent.futures import ThreadPoolExecutor, as_completed

# Static variable for the GeoLite2 City database path
GEOIP_DB_PATH = '/cygdrive/d/pelindo/GeoLite2-City.mmdb'

# Set up argument parser
parser = argparse.ArgumentParser(description='Parse Apache access logs and generate an HTML report of top IP downloads.')
parser.add_argument('log_files', nargs='+', help='Paths to the Apache access log files (can be .gz or plain text)')
args = parser.parse_args()

log_files = args.log_files

# Load the GeoLite2 City database
reader = geoip2.database.Reader(GEOIP_DB_PATH)

# Regex pattern to extract IP, time, size, and status
log_pattern = re.compile(r'(?P<ip>\d+\.\d+\.\d+\.\d+) - - \[(?P<time>.+?)\] "(?P<method>\S+) (?P<url>\S+) .+?" (?P<status>\d+) (?P<size>\d+) ".+?" "(?P<user_agent>.+?)"')

# Helper function to extract date in 'YYYY-MM-DD' format
def extract_date(log_time):
    return datetime.strptime(log_time.split()[0], "%d/%b/%Y:%H:%M:%S").strftime("%Y-%m-%d")

# Helper function to open gzipped or plain text log files
def open_log_file(log_file):
    if log_file.endswith('.gz'):
        return gzip.open(log_file, 'rt')  # Open gzipped file in text mode
    else:
        return open(log_file, 'r')  # Open regular text file

# Function to process a single log file
def process_log_file(log_file):
    downloads_by_date = defaultdict(lambda: defaultdict(int))  # Track downloads by date and IP

    with open_log_file(log_file) as f:
        for line in f:
            match = log_pattern.match(line)
            if match:
                ip = match.group('ip')
                log_time = match.group('time')
                size = int(match.group('size'))
                status = match.group('status')
                date = extract_date(log_time)

                # Only consider requests with HTTP status code 200
                if status == '200':
                    downloads_by_date[date][ip] += size  # Accumulate download sizes by IP

    return downloads_by_date

# Process log files concurrently
downloads_by_date_combined = defaultdict(lambda: defaultdict(int))

with ThreadPoolExecutor(max_workers=5) as executor:
    future_to_file = {executor.submit(process_log_file, log_file): log_file for log_file in log_files}

    for future in as_completed(future_to_file):
        log_file = future_to_file[future]
        try:
            downloads_by_date = future.result()
            # Combine results from each thread into the combined dictionary
            for date, ip_data in downloads_by_date.items():
                for ip, bytes_downloaded in ip_data.items():
                    downloads_by_date_combined[date][ip] += bytes_downloaded
        except Exception as exc:
            print(f'Error processing {log_file}: {exc}')

# Sort dates in chronological order
sorted_dates = sorted(downloads_by_date_combined.keys())

# Generate HTML content
html_content = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Top 15 IP Downloads</title>
    <style>
        body {{
            font-family: 'Arial', sans-serif;
            background-color: #f7f9fc;
            color: #333;
            margin: 0;
            padding: 0;
        }}
        h1 {{
            background-color: #4b6584;
            color: white;
            padding: 20px;
            text-align: center;
        }}
        h2 {{
            color: #4b6584;
            margin: 20px;
        }}
        table {{
            width: 800px;
            margin: 0 auto 20px auto;
            border-collapse: collapse;
        }}
        th, td {{
            padding: 10px;
            border: 1px solid #ccc;
            text-align: left;
        }}
        th {{
            background-color: #f0f5f9;
            color: #4b6584;
        }}
        tr:nth-child(even) {{
            background-color: #f9f9f9;
        }}
        tr:hover {{
            background-color: #e3f2fd;
        }}
        .footer {{
            text-align: center;
            padding: 10px;
            background-color: #f0f5f9;
            margin-top: 20px;
        }}
    </style>
</head>
<body>
    <h1>Top 15 IP Addresses by Total MB Downloaded</h1>
    {date_sections}
    <div class="footer">
        <p>Generated by Apache Log Parser</p>
    </div>
</body>
</html>
"""

# Generate sections for each date
date_sections = ""

for date in sorted_dates:
    # Sort IPs by total bytes downloaded in descending order and select the top 15
    sorted_ips = sorted(downloads_by_date_combined[date].items(), key=lambda x: x[1], reverse=True)[:15]

    # Query GeoLite2 City database for city and country information for the top 15 IPs
    ip_rows = ""
    for ip, bytes_downloaded in sorted_ips:
        total_mb = bytes_downloaded / 1_048_576  # Convert bytes to MB
        try:
            response = reader.city(ip)
            country = response.country.name if response.country.name else "Unknown"
            city = response.city.name if response.city.name else "Unknown"
        except geoip2.errors.AddressNotFoundError:
            country = "Unknown"
            city = "Unknown"

        ip_rows += f"<tr><td>{ip}</td><td>{country}</td><td>{city}</td><td>{total_mb:.2f} MB</td></tr>"

    # Add section for this date
    date_section = f"""
    <h2>Top 15 IP Addresses for {date}</h2>
    <table>
        <tr><th>IP Address</th><th>Country</th><th>City</th><th>Total MB Downloaded</th></tr>
        {ip_rows}
    </table>
    """
    
    date_sections += date_section

# Output filename based on the first log file's name
base_name = os.path.basename(log_files[0])
output_file_name = f"top_15_ip_downloads_by_date_{base_name}.html"

# Write to an HTML file
with open(output_file_name, 'w') as f:
    f.write(html_content.format(date_sections=date_sections))

# Close the GeoLite2 reader
reader.close()

print(f"HTML report '{output_file_name}' generated successfully.")
