import re
import os
import gzip
import argparse
from collections import defaultdict
from datetime import datetime
from concurrent.futures import ThreadPoolExecutor, as_completed

# Set up argument parser
parser = argparse.ArgumentParser(description='Parse Apache access logs and generate an HTML report of top URLs by total hits and associated IP addresses.')
parser.add_argument('log_files', nargs='+', help='Paths to the Apache access log files (can be .gz or plain text)')
args = parser.parse_args()

log_files = args.log_files

# Regex pattern to extract IP, time, URL, status code
log_pattern = re.compile(
    r'(?P<ip>\d+\.\d+\.\d+\.\d+) - - \[(?P<time>.+?)\] "(?P<method>\S+) (?P<url>\S+) .+?" (?P<status>\d+) (?P<size>\d+) ".+?" ".+"'
)

# Function to extract the first subdirectory from a URL
def get_first_subdirectory(url):
    parts = url.split('/')
    return '/' + parts[1] if len(parts) > 1 else url

# Function to process a single log file
def process_log_file(log_file):
    urls_by_date = defaultdict(lambda: defaultdict(lambda: defaultdict(int)))  # URL hits by date and IP

    # Helper function to extract date in 'YYYY-MM-DD' format
    def extract_date(log_time):
        return datetime.strptime(log_time.split()[0], "%d/%b/%Y:%H:%M:%S").strftime("%Y-%m-%d")

    # Helper function to open gzipped or plain text log files
    def open_log_file(log_file):
        if log_file.endswith('.gz'):
            return gzip.open(log_file, 'rt')  # Open gzipped file in text mode
        else:
            return open(log_file, 'r')  # Open regular text file

    with open_log_file(log_file) as f:
        for line in f:
            match = log_pattern.match(line)
            if match:
                ip = match.group('ip')
                log_time = match.group('time')
                url = match.group('url')
                date = extract_date(log_time)
                status = match.group('status')

                # Only consider requests with HTTP status code 200
                if status == '200':
                    first_subdirectory = get_first_subdirectory(url)
                    urls_by_date[date][first_subdirectory][ip] += 1

    return urls_by_date

# Process log files concurrently
urls_by_date_combined = defaultdict(lambda: defaultdict(lambda: defaultdict(int)))

with ThreadPoolExecutor(max_workers=5) as executor:
    future_to_file = {executor.submit(process_log_file, log_file): log_file for log_file in log_files}

    for future in as_completed(future_to_file):
        log_file = future_to_file[future]
        try:
            urls_by_date = future.result()
            # Combine results into urls_by_date_combined
            for date, url_data in urls_by_date.items():
                for url, ip_data in url_data.items():
                    for ip, hits in ip_data.items():
                        urls_by_date_combined[date][url][ip] += hits
        except Exception as exc:
            print(f'{log_file} generated an exception: {exc}')

# Sort dates in chronological order
sorted_dates = sorted(urls_by_date_combined.keys())

# Generate HTML content
html_content = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Top URLs</title>
    <style>
        body {{
            font-family: 'Arial', sans-serif;
            background-color: #f7f9fc;
            color: #333;
            margin: 0;
            padding: 0;
        }}
        h1 {{
            background-color: #4b6584;
            color: white;
            padding: 20px;
            text-align: center;
        }}
        h2 {{
            color: #4b6584;
            margin: 20px;
        }}
        table {{
            width: 800px;
            margin: 0 auto 20px auto;
            border-collapse: collapse;
        }}
        th, td {{
            padding: 10px;
            border: 1px solid #ccc;
            text-align: left;
        }}
        th {{
            background-color: #f0f5f9;
            color: #4b6584;
        }}
        tr:nth-child(even) {{
            background-color: #f9f9f9;
        }}
        tr:hover {{
            background-color: #e3f2fd;
        }}
        .footer {{
            text-align: center;
            padding: 10px;
            background-color: #f0f5f9;
            margin-top: 20px;
        }}
    </style>
</head>
<body>
    <h1>Top URLs by Total Hits</h1>
    {date_sections}
    <div class="footer">
        <p>Generated by Apache Log Parser</p>
    </div>
</body>
</html>
"""

# Generate sections for each date
date_sections = ""

for date in sorted_dates:
    # Sort URLs by total hits in descending order and limit to the top 15
    sorted_urls = sorted(urls_by_date_combined[date].items(), key=lambda x: sum(x[1].values()), reverse=True)[:15]

    # Prepare rows for the HTML table
    url_rows = ""
    for url, ip_data in sorted_urls:
        total_hits = sum(ip_data.values())
        ip_list = ", ".join(ip_data.keys())  # Collect all associated IPs
        url_rows += f"<tr><td>{url}</td><td>{ip_list}</td><td>{total_hits}</td></tr>"

    # Add section for this date
    date_section = f"""
    <h2>Top URLs for {date}</h2>
    <table>
        <tr><th>URL Path</th><th>Associated IPs</th><th>Total Hits</th></tr>
        {url_rows}
    </table>
    """
    
    date_sections += date_section

# Output filename based on the first log file's name
base_name = os.path.basename(log_files[0])
output_file_name = f"top_urls_by_date_{base_name}.html"

# Write to an HTML file
with open(output_file_name, 'w') as f:
    f.write(html_content.format(date_sections=date_sections))

print(f"HTML report '{output_file_name}' generated successfully.")
